server:
  port: ${ORDER_SERVICE_PORT:8081}

spring:
  http:
    serviceclient:
      inventory:
        base-url: ${INVENTORY_SERVICE_URL:http://localhost:8082}
        connect-timeout: 2s
        read-timeout: 3s


  config:
    import:
      - optional:file:.env[.properties]
      - optional:file:../.env[.properties]

  application:
    name: order-service

  datasource:
    url: jdbc:postgresql://${ORDER_DB_HOST:localhost}:${ORDER_DB_PORT:5433}/${ORDER_DB_NAME:order_db}
    username: ${ORDER_DB_USERNAME:order_user}
    password: ${ORDER_DB_PASSWORD:order_password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

  kafka:

    bootstrap-servers: localhost:${KAFKA_EXTERNAL_PORT}
    producer:
      client-id: order-service-outbox-producer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        "[enable.idempotence]": true

    consumer:
      group-id: order-inventory-reservation-v1
      enable-auto-commit: false
      auto-offset-reset: earliest

      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      max-poll-records: 50


    listener:
      type: single
      ack-mode: batch
      concurrency: 1

app:
  kafka:
    topics:
      order-events: order.events
      inventory-events: inventory.events
      inventory-events-dlt: inventory.events.order-service.dlt

  outbox:
    polling:
      batch-size: 50
      fixed-delay-ms: 5000
      processing-timeout-ms: 60000


logging:
  level:
    org.hibernate.SQL: debug
    org.apache.kafka: INFO