server:
  port: ${ORDER_SERVICE_PORT:8081}

spring:
  config:
    import:
      - optional:file:.env[.properties]
      - optional:file:../.env[.properties]

  application:
    name: order-service

  datasource:
    url: jdbc:postgresql://${ORDER_DB_HOST:localhost}:${ORDER_DB_PORT:5433}/${ORDER_DB_NAME:order_db}
    username: ${ORDER_DB_USERNAME:order_user}
    password: ${ORDER_DB_PASSWORD:order_password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

logging:
  level:
    org.hibernate.SQL: debug