server:
  port: ${INVENTORY_SERVICE_PORT:8082}

spring:
  config:
    import:
      - optional:file:.env[.properties]
      - optional:file:../.env[.properties]

  application:
    name: inventory-service

  datasource:
    url: jdbc:postgresql://${INVENTORY_DB_HOST:localhost}:${INVENTORY_DB_PORT:5434}/${INVENTORY_DB_NAME:inventory_db}
    username: ${INVENTORY_DB_USERNAME}
    password: ${INVENTORY_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

    consumer:
      group-id: inventory-order-created-v1
      enable-auto-commit: false
      auto-offset-reset: earliest

      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      max-poll-records: 50

    producer:
      client-id: inventory-service-outbox-producer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

      acks: all

      properties:
        enable.idempotence: true

    listener:
      type: single
      ack-mode: batch  # так как настроена идемпотентная обработка сообщений
      concurrency: 1

app:
  kafka:
    topics:
      order-events: order.events
      order-events-dlt: order.events.inventory-service.dlt
      inventory-events: inventory.events

  outbox:
    polling:
      batch-size: 50
      fixed-delay-ms: 5000
      processing-timeout-ms: 60000

logging:
  level:
    org.hibernate.SQL: debug